# Generated by Django 5.2.7 on 2026-02-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='image',
        ),
    ]
